### PR TITLE
pt_BR strings

### PR DESCRIPTION
**Pull request by aevw**
Translated strings for Island in pt_BR

### CODE REVIEW

**Comment by aevw** [comment]
Related to issue #130

**Comment by oasisfeng** [comment]
Sorry, but I cannot find the translation XMLs in your PR commits.

Looks like files are incorrect?

**Comment by aevw** [comment]
Hello, I revised it again and uploaded with 'is' name. Hope it can be useful & implemented.

[pt_BR](https://github.com/aevw/RD-pt_BR/blob/master/is.xml)

Thanks

**Comment by oasisfeng** [comment]
But your files are not included in this PR (see "Files changed" section of this PR). Did you create the PR from the right branch?

**Comment by aevw** [comment]
Hello, I made another PR & I will close this one, hopefully it'll work

**Comment by aevw** [comment]
See #156

**Pull request closed without merging**
