### PR TITLE
Create strings.xml

### PR DESCRIPTION
**Pull request by ghost**
pt_BR strings

### CODE REVIEW

**Comment by bluehomewu** [comment]
Not only this files,check my PR #140

**Comment by aevw** [comment]
Hello devs,

So I had to redo strings for mobile because it was taken from main branch & not dev.

& added strings from:
+1) engine/src/main/res/values/strings.xml
+2) fileprovider/src/main/res/values/strings.xml
+3) mobile/src/main/res/values/strings.xml
+4) open/src/main/res/values/strings.xml
+5) shared/src/main/res/values/strings.xml
+6) watcher/src/main/res/values/strings.xml
+7) installer/src/main/res/values/strings.xml

Total 7.

Let me know if I missed something. Thanks

**Comment by proletarius101** [comment]
Is there anything left?

**Comment by oasisfeng** [comment]
Sorry, I was misled by the title and missed this high quality PR.
Unfortunately I have already merged another newer translation in pt-br, thus I have to close this one.

Really sorry for that and thanks for your contribution!

**Pull request closed without merging**
