### PR TITLE
Added password and clipboard settings.

### PR DESCRIPTION
**Pull request by agreenbhm**
Added the ability to wipe the Island profile based on a user-defined number of failed password attempts for the Main profile and/or Island profile. For example: 5 failed unlock attempts of the Main profile trigger a wipe of Island, and 2 failed unlock attempts of the Island profile trigger a wipe of the Island. Also added ability to set password within app (make sure you disable "one password" in phone settings first though, otherwise you will change the password for both). 

Added a setting to prevent sharing of clipboard data between profiles. Need to configure this in scoped settings of each profile you want to prevent data from leaving, ie set it in scoped settings for the Island profile to prevent the Main profile from accessing the Island clipboard, and vice-versa. Setting this in the Main profile requires Demi-God or God Mode to be enabled. Motivation for this was to prevent Tiktok from stealing clipboard data from Main profile when running Tiktok in Island.

### CODE REVIEW

**Comment by oasisfeng** [comment]
Thanks for your contribution.

As this is a relatively large pull request, I may need more time to review it. Thanks for your patience.

**Comment by oasisfeng** [comment]
Due to the ongoing major development for supporting multiple Islands, review for this pull request will be postponed to mid-Aug.

Sorry for the delay.

**Comment by oasisfeng** [comment]
I think the clipboard (copy-paste) restriction should not be applied by default, as it is counter-intuitive, at least for average users.

**Comment by agreenbhm** [comment]
> I think the clipboard (copy-paste) restriction should not be applied by default, as it is counter-intuitive, at least for average users.

I think that's a fair point.  What is the best way to make that happen? Should I update the changes in my repo to reflect this?

**Comment by oasisfeng** [comment]
After review, I think there's some more changes need to be made:

* `startDeviceAndProfileOwnerSharedPostProvisioning()` is shared by both profile owner and device owner provisioning, your changes are not suitable for device owner.
* Provisioning procedure will also be executed incrmentally after Island is setup, thus must be imdempotent and must not reset user-changed settings. (I'd suggest to avoid applying user-customizable restrictions in provisioning)
* `IslandSettingsFragment` is per-Island settings (if multiple-Islands are setup), parent-password policy settings may not be suitable there. (I haven't tested this scenario where multiple Islands have different parent-password policy settings)
* Some minor conflicts need to be resolved after `dev` branch is updated recently. (`dev` will be in relatively stable state for a while)

Thanks again for your contribution. I'm grateful to merge it afterwards.

**Comment by chri5t** [comment]
I am uncertain if this is the same topic as adding **password protection** to the app before it opens.. 
I sure hope it is.. This app helps in the sense that it separates all my banking, medical apps, and shopping store apps separate from all the other garbage i tend download on the mainland. Since all these apps on android collect data from each other i am glad to have something like this to keep my private info from being spyed or leaked by all the other apps from the mainland. I wanted to also suggest if there is a way while in island mode  to restrict or ban apps from taking screenshots/captures as well as prevent them too from spying on each other to an extent..
Thanx for making one of the best DualApp programs out there.

**Comment by oasisfeng** [comment]
> I am uncertain if this is the same topic as adding **password protection** to the app before it opens..
> I sure hope it is.. This app helps in the sense that it separates all my banking, medical apps, and shopping store apps separate from all the other garbage i tend download on the mainland. Since all these apps on android collect data from each other i am glad to have something like this to keep my private info from being spyed or leaked by all the other apps from the mainland. I wanted to also suggest if there is a way while in island mode to restrict or ban apps from taking screenshots/captures as well as prevent them too from spying on each other to an extent since my banks would love to check what my spending habbits are.. Another contribution is the option to require password authorization again from selected apps in the island just incase island is left open on the phone by mistake or perhaps to have the option to automatically exit from island and exit any apps open from it if there is no activity for _?_ many minutes the user places down from settings.
> Thanx for making one of the best DualApp programs out there.

It's not.

You can create separate password or pin for your Island, different from Mainland.
It's applied to the whole Island and requires password or pin when app in Island is first started. To lock down the Island (re-prompt password or pin), you can "Deactivate" the Island.

**Comment by oasisfeng** [comment]
@agreenbhm This PR contains multiple independent features. I think not all of them are ready for the current stage of Island development.

I will partially copy some of the features in your PR, but that could not be done via the GitHub merge process, so I am closing this PR.

Please consider contributing multiple independent features with separate PR. Thanks again for your contribution!

**Pull request closed without merging**
